### ISSUE TITLE
Unable to download package

### ISSUE THREAD

**Issue by ursusbob** [poissonconsulting/bboutools#12]
When running `devtools::install_github("poissonconsulting/bboutools")`
I get the error:

> Downloading GitHub repo poissonconsulting/bboutools@HEAD
> Error: Failed to install 'bboutools' from GitHub:
>   HTTP error 404.
>   Not Found
> 
>   Did you spell the repo owner (`poissonconsulting`) and repo name (`bboudata`) correctly?
>   - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by ursusbob** [comment]
I have been able to install other packages from GitHub

**Comment by sebdalgarno** [comment]
@ursusbob are you still having this issue?

**Comment by aylapear** [comment]
This should be corrected now that the package is public
