### ISSUE TITLE
add section in bbmethods vignette on benefits of random effects and shrinkage

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/bboutools#24]
i.e. add to this section 

## Fixed vs Random Effects

When a categorical variable is treated as a fixed effect each parameter values is estimated in isolation.
In contrast, when it is treated as a random effect the parameter values are assumed to be drawn from a common underlying distribution which allows the typical values to be estimated and each parameter estimate to be influenced by the other ones.

**Comment by sebdalgarno** [comment]
perhaps something like this @joethorley ?:

The use of random effects is especially beneficial in cases where some months/years have sparse or missing data. In the case of sparse data, estimates will tend to be pulled toward the mean in a process called 'shrinkage'.  For missing data, the estimate will be equal to the mean. 'Shrinkage' may not be desired if extreme values are likely to represent the true value (e.g., numerous wolf attacks in one year). In this case, a fixed effect model should be fitted.

**Comment by sebdalgarno** [comment]
see https://poissonconsulting.github.io/bboutools/articles/bbmethods.html for full vignette and context

**Comment by joethorley** [comment]
@sebdalgarno - I like that!
